server:
  port: 3333
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.163:3306/maintain?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      password: asd1345439
      username: root
      db-type: mysql